const cars = [
    {
      id: 1,
      start: 'Kigali',
      end: 'Rwamagana',
      time: '06:00 - 08:00',
      cost: 5000,
    },
    {
      id: 2,
      start: 'Kigali',
      end: 'Musanze',
      time: '08:00 - 10:00',
      cost: 3000,
    },
    {
      id: 3,
      start: 'Rwamagana',
      end: 'Gakenke',
      time: '09:00 - 11:00',
      cost: 4000,
    },
    {
      id: 4,
      start: 'Musanze',
      end: 'Ruhengeri',
      time: '10:00 - 12:00',
      cost: 2500,
    },
    {
      id: 5,
      start: 'Gakenke',
      end: 'Gatagara',
      time: '11:00 - 13:00',
      cost: 3500,
    },
    {
      id: 6,
      start: 'Ruhengeri',
      end: 'Kibuye',
      time: '12:00 - 14:00',
      cost: 4500,
    },
    {
      id: 7,
      start: 'Kigali',
      end: 'Huye',
      time: '13:00 - 15:00',
      cost: 5500,
    },
    {
      id: 8,
      start: 'Huye',
      end: 'Nyagatare',
      time: '14:00 - 16:00',
      cost: 6500,
    },
    {
      id: 9,
      start: 'Nyagatare',
      end: 'Gatsineza',
      time: '15:00 - 17:00',
      cost: 7500,
    },
  ];
  
  const districts = [
     { name:'Bugesera', code:'01' },
     { name:'Gatsibo', code:'02' },
     { name:'Gakenke', code:'03' },
     { name:'Gatagara', code:'04' },
     { name:'Kayonza', code:'05' },
     { name:'Kibuye', code:'06' },
     { name:'Kigali', code:'07' },
     { name:'Kirehe', code:'08' },
     { name:'Musanze', code:'09' },
     { name:'Ngoma', code:'10' },
     { name:'Nyanza', code:'11' },
     { name:'Nyamasheke', code:'12' },
     { name:'Nyarugenge', code:'13' },
     { name:'Nyungwe', code:'14' },
     { name:'Ruhengeri', code:'15' },
     { name:'Rwamagana', code:'16' },
     { name:'Rwanda (central)', code:'17' },
     { name:'Rusizi', code:'18' }, 
     { name:'Rutsiro', code:'19' }, 
     { name:'Gasabo', code :'20'}, 
     { name :'Gicumbi ',code :'21'},
     { name :'Rubavu ',code :'22'},
     { name :'Burera ',code :'23'},
     { name :'Musaze ',code :'24'},
     { name :'Gisagara ',code :'25'},
     { name :'Kamembe ',code :'26'},
     { name :'Nyamasheke ',code :'27'},
  ];